[serve.static]
plugins = [
  "./plugins/solid-bun-plugin.ts",
  "./plugins/unocss-bun-plugin.ts",
]

[test]
root = "./tests/real"
coverage = true
preload = [ "./tests/setup/happy-dom.ts" ]
coverageSkipTestFiles = true
coveragePathIgnorePatterns = [ "tests/**" ]
